#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [17]:
# !pip install numpy
import numpy as np

In [18]:
## create an array using numpy
# Create a 1D array
arr1 = np.array([1,2,3,4,6,8,9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 6 8 9]
<class 'numpy.ndarray'>
(7,)


In [19]:
arr2 = np.array([1,2,4,5,7,8,9])
arr2.reshape(1,7)  ## In the output we can see the [[]]; it's a 2D array

array([[1, 2, 4, 5, 7, 8, 9]])

In [20]:
arr2 = np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

In [21]:
# 2D numpy array
arr2 = np.array([[1,2,3,4,5,6], [2,3,4,6,7,8]])
print(arr2)
print(f"Shape of numpy array: {arr2.shape}")
print(arr2[1])

[[1 2 3 4 5 6]
 [2 3 4 6 7 8]]
Shape of numpy array: (2, 6)
[2 3 4 6 7 8]


In [23]:
np.arange(0,10,2).reshape(5,1) #start, stop, step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
# This is a 2D numpy array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
## identity matrix: numpy.eye() function in NumPy is used to create a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(3) # 3 * 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
## Attributes of Numpy Array
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])

print("Array:\n", arr)
print("Shape:", arr.shape) 
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size) 
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)  


Array:
 [[1 2 3 4 5]
 [4 5 6 7 8]]
Shape: (2, 5)
Number of dimensions: 2
Size (number of elements): 10
Data type: int64
Item size (in bytes): 8


In [39]:
### Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print(f"Addition: {arr1 + arr2}")

## Element wise substraction
print(f"substraction: {arr2 - arr1}")

## Element wise multiply
print(f"Multiplication: {arr1 * arr2}")

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
substraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [44]:
# Universal functions
arr = np.array([1,2,43,46,7,36])

#square root
print(f"SQRT {np.sqrt(arr)}")

#Exponential
print(f" Exponential {np.exp(arr)}")

#Sine
print(f" Sine {np.sin(arr)}")

## natural log
print(f" log {np.log(arr)}")

SQRT [1.         1.41421356 6.55743852 6.78232998 2.64575131 6.        ]
 Exponential [2.71828183e+00 7.38905610e+00 4.72783947e+18 9.49611942e+19
 1.09663316e+03 4.31123155e+15]
 Sine [ 0.84147098  0.90929743 -0.83177474  0.90178835  0.6569866  -0.99177885]
 log [0.         0.69314718 3.76120012 3.8286414  1.94591015 3.58351894]


In [54]:
# array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
#print(arr[0][3])
print(arr[1:3, 2:])

print("2nd Array",arr[1:, 1:3])

[[ 7  8]
 [11 12]]
2nd Array [[ 6  7]
 [10 11]]


In [69]:
print(arr[:2, 2: ])

[[  3   4]
 [100 100]]


In [70]:
## Modify array elements
arr[0, 0] = 100
print(arr)

arr[1:] = 100

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [75]:
### statistical concepts--Normalization
##TO have a mean of 0 and standard deviation of 1 
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean_sol = np.mean(data)
std_sol = np.std(data)

print("Mean:", mean_sol)
print("Standard deviation:", std_sol)


# Normalize the data
normalized_data = (data - mean_sol) / std_sol
print("Normalized data:", normalized_data)

Mean: 3.0
Standard deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [76]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [77]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

: 